//
//  EditPlan.swift
//  MetalCraft
//
//  Core AI-to-Editor contract schema.
//  Strongly-typed Codable and Sendable models representing structured
//  editing plans generated by the Gemini Creative Director.
//

import Foundation

// MARK: - Polymorphic AnyCodableValue

enum AnyCodableValue: Codable, Sendable, Equatable {
    case string(String)
    case int(Int)
    case double(Double)
    case bool(Bool)
    case array([AnyCodableValue])
    case dictionary([String: AnyCodableValue])
    case null
    
    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        
        if container.decodeNil() {
            self = .null
        } else if let boolVal = try? container.decode(Bool.self) {
            self = .bool(boolVal)
        } else if let intVal = try? container.decode(Int.self) {
            self = .int(intVal)
        } else if let doubleVal = try? container.decode(Double.self) {
            self = .double(doubleVal)
        } else if let stringVal = try? container.decode(String.self) {
            self = .string(stringVal)
        } else if let arrayVal = try? container.decode([AnyCodableValue].self) {
            self = .array(arrayVal)
        } else if let dictVal = try? container.decode([String: AnyCodableValue].self) {
            self = .dictionary(dictVal)
        } else {
            throw DecodingError.dataCorruptedError(in: container, debugDescription: "Unsupported AnyCodableValue type")
        }
    }
    
    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .string(let s):
            try container.encode(s)
        case .int(let i):
            try container.encode(i)
        case .double(let d):
            try container.encode(d)
        case .bool(let b):
            try container.encode(b)
        case .array(let a):
            try container.encode(a)
        case .dictionary(let d):
            try container.encode(d)
        case .null:
            try container.encodeNil()
        }
    }
    
    var stringValue: String? {
        if case .string(let s) = self { return s }
        return nil
    }
    
    var doubleValue: Double? {
        switch self {
        case .double(let d): return d
        case .int(let i): return Double(i)
        default: return nil
        }
    }
    
    var floatValue: Float? {
        if let d = doubleValue { return Float(d) }
        return nil
    }
    
    var intValue: Int? {
        switch self {
        case .int(let i): return i
        case .double(let d): return Int(d)
        default: return nil
        }
    }
    
    var boolValue: Bool? {
        if case .bool(let b) = self { return b }
        return nil
    }
}

// MARK: - EditPlan Adjustments

struct EditPlanAdjustments: Codable, Sendable, Equatable {
    var brightness: Float
    var contrast: Float
    var exposure: Float
    var saturation: Float
    var temperature: Float
    var tint: Float
    var gamma: Float
    
    init(
        brightness: Float = 0.0,
        contrast: Float = 1.0,
        exposure: Float = 0.0,
        saturation: Float = 1.0,
        temperature: Float = 0.0,
        tint: Float = 0.0,
        gamma: Float = 1.0
    ) {
        self.brightness = brightness
        self.contrast = contrast
        self.exposure = exposure
        self.saturation = saturation
        self.temperature = temperature
        self.tint = tint
        self.gamma = gamma
    }
    
    static let `default` = EditPlanAdjustments()
}

// MARK: - EditPlan Operation

struct EditPlanOperation: Identifiable, Codable, Sendable, Equatable {
    var id: UUID
    var type: String
    var enabled: Bool
    var parameters: [String: AnyCodableValue]
    
    init(
        id: UUID = UUID(),
        type: String,
        enabled: Bool = true,
        parameters: [String: AnyCodableValue] = [:]
    ) {
        self.id = id
        self.type = type
        self.enabled = enabled
        self.parameters = parameters
    }
    
    enum CodingKeys: String, CodingKey {
        case id
        case type
        case enabled
        case parameters
    }
    
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decodeIfPresent(UUID.self, forKey: .id) ?? UUID()
        self.type = try container.decode(String.self, forKey: .type)
        self.enabled = try container.decodeIfPresent(Bool.self, forKey: .enabled) ?? true
        self.parameters = try container.decodeIfPresent([String: AnyCodableValue].self, forKey: .parameters) ?? [:]
    }
}

// MARK: - EditPlan Output

struct EditPlanOutput: Codable, Sendable, Equatable {
    var format: String
    var quality: Float
    var aspectRatio: String?
    
    init(
        format: String = "jpeg",
        quality: Float = 0.95,
        aspectRatio: String? = nil
    ) {
        self.format = format
        self.quality = quality
        self.aspectRatio = aspectRatio
    }
    
    static let `default` = EditPlanOutput()
}

// MARK: - EditPlan (Root Contract)

struct EditPlan: Identifiable, Codable, Sendable, Equatable {
    var id: String { planId }
    var schemaVersion: String
    var planId: String
    var createdAt: Date
    var mediaType: MediaType
    var goal: String
    var reasoning: String
    var researchContext: String?
    var adjustments: EditPlanAdjustments
    var operations: [EditPlanOperation]
    var output: EditPlanOutput
    
    init(
        schemaVersion: String = "1.0",
        planId: String = UUID().uuidString,
        createdAt: Date = Date(),
        mediaType: MediaType = .image,
        goal: String,
        reasoning: String = "",
        researchContext: String? = nil,
        adjustments: EditPlanAdjustments = .default,
        operations: [EditPlanOperation] = [],
        output: EditPlanOutput = .default
    ) {
        self.schemaVersion = schemaVersion
        self.planId = planId
        self.createdAt = createdAt
        self.mediaType = mediaType
        self.goal = goal
        self.reasoning = reasoning
        self.researchContext = researchContext
        self.adjustments = adjustments
        self.operations = operations
        self.output = output
    }
}
