//
//  EditPlan.swift
//  MetalCraft
//
//  Core AI-to-Editor contract schema.
//  Strongly-typed Codable and Sendable models representing structured
//  editing plans generated by the Gemini Creative Director.
//  Supports single-image, single-video, and multi-asset project video timelines.
//

import Foundation

// MARK: - Polymorphic AnyCodableValue

enum AnyCodableValue: Codable, Sendable, Equatable {
    case string(String)
    case int(Int)
    case double(Double)
    case bool(Bool)
    case array([AnyCodableValue])
    case dictionary([String: AnyCodableValue])
    case null
    
    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        
        if container.decodeNil() {
            self = .null
        } else if let boolVal = try? container.decode(Bool.self) {
            self = .bool(boolVal)
        } else if let intVal = try? container.decode(Int.self) {
            self = .int(intVal)
        } else if let doubleVal = try? container.decode(Double.self) {
            self = .double(doubleVal)
        } else if let stringVal = try? container.decode(String.self) {
            self = .string(stringVal)
        } else if let arrayVal = try? container.decode([AnyCodableValue].self) {
            self = .array(arrayVal)
        } else if let dictVal = try? container.decode([String: AnyCodableValue].self) {
            self = .dictionary(dictVal)
        } else {
            throw DecodingError.dataCorruptedError(in: container, debugDescription: "Unsupported AnyCodableValue type")
        }
    }
    
    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .string(let s):
            try container.encode(s)
        case .int(let i):
            try container.encode(i)
        case .double(let d):
            try container.encode(d)
        case .bool(let b):
            try container.encode(b)
        case .array(let a):
            try container.encode(a)
        case .dictionary(let d):
            try container.encode(d)
        case .null:
            try container.encodeNil()
        }
    }
    
    var stringValue: String? {
        if case .string(let s) = self { return s }
        return nil
    }
    
    var doubleValue: Double? {
        switch self {
        case .double(let d): return d
        case .int(let i): return Double(i)
        default: return nil
        }
    }
    
    var floatValue: Float? {
        if let d = doubleValue { return Float(d) }
        return nil
    }
    
    var intValue: Int? {
        switch self {
        case .int(let i): return i
        case .double(let d): return Int(d)
        default: return nil
        }
    }
    
    var boolValue: Bool? {
        if case .bool(let b) = self { return b }
        return nil
    }
}

// MARK: - EditPlan Adjustments

struct EditPlanAdjustments: Codable, Sendable, Equatable {
    var brightness: Float
    var contrast: Float
    var exposure: Float
    var saturation: Float
    var temperature: Float
    var tint: Float
    var gamma: Float
    
    init(
        brightness: Float = 0.0,
        contrast: Float = 1.0,
        exposure: Float = 0.0,
        saturation: Float = 1.0,
        temperature: Float = 0.0,
        tint: Float = 0.0,
        gamma: Float = 1.0
    ) {
        self.brightness = brightness
        self.contrast = contrast
        self.exposure = exposure
        self.saturation = saturation
        self.temperature = temperature
        self.tint = tint
        self.gamma = gamma
    }
    
    enum CodingKeys: String, CodingKey {
        case brightness, contrast, exposure, saturation, temperature, tint, gamma
        case highlights, shadows, sharpness
    }
    
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.brightness = Self.decodeFloat(container, key: .brightness, default: 0.0)
        self.contrast = Self.decodeFloat(container, key: .contrast, default: 1.0)
        self.exposure = Self.decodeFloat(container, key: .exposure, default: 0.0)
        self.saturation = Self.decodeFloat(container, key: .saturation, default: 1.0)
        self.temperature = Self.decodeFloat(container, key: .temperature, default: 0.0)
        self.tint = Self.decodeFloat(container, key: .tint, default: 0.0)
        self.gamma = Self.decodeFloat(container, key: .gamma, default: 1.0)
    }
    
    private static func decodeFloat(_ container: KeyedDecodingContainer<CodingKeys>, key: CodingKeys, default def: Float) -> Float {
        if let val = try? container.decodeIfPresent(Float.self, forKey: key) { return val }
        if let val = try? container.decodeIfPresent(Double.self, forKey: key) { return Float(val) }
        if let str = try? container.decodeIfPresent(String.self, forKey: key), let parsed = Float(str) { return parsed }
        return def
    }
    
    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(brightness, forKey: .brightness)
        try container.encode(contrast, forKey: .contrast)
        try container.encode(exposure, forKey: .exposure)
        try container.encode(saturation, forKey: .saturation)
        try container.encode(temperature, forKey: .temperature)
        try container.encode(tint, forKey: .tint)
        try container.encode(gamma, forKey: .gamma)
    }
    
    static let `default` = EditPlanAdjustments()
}

// MARK: - EditPlan Operation

struct EditPlanOperation: Identifiable, Codable, Sendable, Equatable {
    var id: UUID
    var type: String
    var enabled: Bool
    var parameters: [String: AnyCodableValue]
    
    init(
        id: UUID = UUID(),
        type: String,
        enabled: Bool = true,
        parameters: [String: AnyCodableValue] = [:]
    ) {
        self.id = id
        self.type = type
        self.enabled = enabled
        self.parameters = parameters
    }
    
    enum CodingKeys: String, CodingKey {
        case id, type, enabled, parameters
        case intensity, radius, sigma, scale, frequency, angle, center_x, center_y
    }
    
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        
        if let uuidVal = try? container.decodeIfPresent(UUID.self, forKey: .id) {
            self.id = uuidVal
        } else if let strVal = try? container.decodeIfPresent(String.self, forKey: .id), let parsed = UUID(uuidString: strVal) {
            self.id = parsed
        } else {
            self.id = UUID()
        }
        
        self.type = (try? container.decodeIfPresent(String.self, forKey: .type)) ?? "adjustments"
        self.enabled = (try? container.decodeIfPresent(Bool.self, forKey: .enabled)) ?? true
        
        var params = (try? container.decodeIfPresent([String: AnyCodableValue].self, forKey: .parameters)) ?? [:]
        
        if let intensity = try? container.decodeIfPresent(Double.self, forKey: .intensity) {
            params["intensity"] = .double(intensity)
        }
        if let radius = try? container.decodeIfPresent(Double.self, forKey: .radius) {
            params["radius"] = .double(radius)
        }
        if let sigma = try? container.decodeIfPresent(Double.self, forKey: .sigma) {
            params["sigma"] = .double(sigma)
        }
        if let scale = try? container.decodeIfPresent(Double.self, forKey: .scale) {
            params["scale"] = .double(scale)
        }
        
        self.parameters = params
    }
    
    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(type, forKey: .type)
        try container.encode(enabled, forKey: .enabled)
        try container.encode(parameters, forKey: .parameters)
    }
}

// MARK: - EditPlan Output

struct EditPlanOutput: Codable, Sendable, Equatable {
    var format: String
    var quality: Float
    var aspectRatio: String?
    
    init(
        format: String = "jpeg",
        quality: Float = 0.95,
        aspectRatio: String? = nil
    ) {
        self.format = format
        self.quality = quality
        self.aspectRatio = aspectRatio
    }
    
    enum CodingKeys: String, CodingKey {
        case format, quality, aspectRatio
    }
    
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.format = (try? container.decodeIfPresent(String.self, forKey: .format)) ?? "jpeg"
        self.quality = (try? container.decodeIfPresent(Float.self, forKey: .quality)) ?? 0.95
        self.aspectRatio = try? container.decodeIfPresent(String.self, forKey: .aspectRatio)
    }
    
    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(format, forKey: .format)
        try container.encode(quality, forKey: .quality)
        try container.encodeIfPresent(aspectRatio, forKey: .aspectRatio)
    }
    
    var width: Int {
        if aspectRatio == "16:9" { return 1920 }
        if aspectRatio == "1:1" { return 1080 }
        return 1080
    }
    
    var height: Int {
        if aspectRatio == "16:9" { return 1080 }
        if aspectRatio == "1:1" { return 1080 }
        return 1920
    }
    
    static let `default` = EditPlanOutput()
}

// MARK: - EditPlan Scene (Multi-Scene Timeline)

struct EditPlanScene: Identifiable, Codable, Sendable, Equatable {
    var id: UUID
    var assetId: String?
    var assetType: String      // "image" or "video"
    var assetName: String
    var duration: Double        // in seconds (e.g. 3.0)
    var startTime: Double       // start offset in source video if trimmed
    var transition: String?     // "crossfade", "fadeBlack", "wipe", "dissolve", "none"
    var transitionDuration: Double?
    var adjustments: EditPlanAdjustments?
    var operations: [EditPlanOperation]?
    var zoomEffect: String?     // "zoomIn", "zoomOut", "panLeft", "panRight", "none"
    
    init(
        id: UUID = UUID(),
        assetId: String? = nil,
        assetType: String = "image",
        assetName: String = "Scene Asset",
        duration: Double = 3.0,
        startTime: Double = 0.0,
        transition: String? = "crossfade",
        transitionDuration: Double? = 0.5,
        adjustments: EditPlanAdjustments? = nil,
        operations: [EditPlanOperation]? = nil,
        zoomEffect: String? = "zoomIn"
    ) {
        self.id = id
        self.assetId = assetId
        self.assetType = assetType
        self.assetName = assetName
        self.duration = duration
        self.startTime = startTime
        self.transition = transition
        self.transitionDuration = transitionDuration
        self.adjustments = adjustments
        self.operations = operations
        self.zoomEffect = zoomEffect
    }
    
    enum CodingKeys: String, CodingKey {
        case id, assetId, assetType, assetName, duration, startTime, transition, transitionDuration, adjustments, operations, zoomEffect
        case effectName, transitionType, index
    }
    
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        
        if let uuidVal = try? container.decodeIfPresent(UUID.self, forKey: .id) {
            self.id = uuidVal
        } else if let strVal = try? container.decodeIfPresent(String.self, forKey: .id), let parsed = UUID(uuidString: strVal) {
            self.id = parsed
        } else {
            self.id = UUID()
        }
        
        self.assetId = try? container.decodeIfPresent(String.self, forKey: .assetId)
        self.assetType = (try? container.decodeIfPresent(String.self, forKey: .assetType)) ?? "image"
        self.assetName = (try? container.decodeIfPresent(String.self, forKey: .assetName)) ?? "Scene Asset"
        
        if let d = try? container.decodeIfPresent(Double.self, forKey: .duration) {
            self.duration = d
        } else if let i = try? container.decodeIfPresent(Int.self, forKey: .duration) {
            self.duration = Double(i)
        } else if let s = try? container.decodeIfPresent(String.self, forKey: .duration), let parsed = Double(s) {
            self.duration = parsed
        } else {
            self.duration = 3.0
        }
        
        if let st = try? container.decodeIfPresent(Double.self, forKey: .startTime) {
            self.startTime = st
        } else if let i = try? container.decodeIfPresent(Int.self, forKey: .startTime) {
            self.startTime = Double(i)
        } else {
            self.startTime = 0.0
        }
        
        self.transition = (try? container.decodeIfPresent(String.self, forKey: .transition)) ?? (try? container.decodeIfPresent(String.self, forKey: .transitionType)) ?? "crossfade"
        self.transitionDuration = (try? container.decodeIfPresent(Double.self, forKey: .transitionDuration)) ?? 0.5
        self.adjustments = try? container.decodeIfPresent(EditPlanAdjustments.self, forKey: .adjustments)
        self.operations = try? container.decodeIfPresent([EditPlanOperation].self, forKey: .operations)
        self.zoomEffect = (try? container.decodeIfPresent(String.self, forKey: .zoomEffect)) ?? (try? container.decodeIfPresent(String.self, forKey: .effectName)) ?? "zoomIn"
    }
    
    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(assetId, forKey: .assetId)
        try container.encode(assetType, forKey: .assetType)
        try container.encode(assetName, forKey: .assetName)
        try container.encode(duration, forKey: .duration)
        try container.encode(startTime, forKey: .startTime)
        try container.encodeIfPresent(transition, forKey: .transition)
        try container.encodeIfPresent(transitionDuration, forKey: .transitionDuration)
        try container.encodeIfPresent(adjustments, forKey: .adjustments)
        try container.encodeIfPresent(operations, forKey: .operations)
        try container.encodeIfPresent(zoomEffect, forKey: .zoomEffect)
    }
}

// MARK: - AudioPlan (Soundtrack & Music Mixing Contract)

struct AudioPlan: Codable, Sendable, Equatable {
    var requested: Bool
    var mood: String?           // "cinematic", "emotional", "energetic", "ambient", "corporate", "playful", "luxury", "adventure"
    var style: String?
    var energy: String?         // "low", "medium", "high"
    var duration: Double?       // Target audio duration in seconds
    var source: String          // "metalcraft_library", "project_music", "imported", "none"
    var trackId: String?        // Controlled track ID (e.g. "cinematic_emotional_01", "corporate_tech_01")
    var trackTitle: String?     // Human-readable title
    var volume: Float           // [0.0 ... 1.0], default 0.7
    var fadeInDuration: Double  // in seconds, e.g. 0.5
    var fadeOutDuration: Double // in seconds, e.g. 1.0
    var duckingFactor: Float    // [0.0 ... 1.0] when dialogue or original audio is present
    
    init(
        requested: Bool = false,
        mood: String? = "cinematic",
        style: String? = "cinematic",
        energy: String? = "medium",
        duration: Double? = nil,
        source: String = "metalcraft_library",
        trackId: String? = nil,
        trackTitle: String? = nil,
        volume: Float = 0.7,
        fadeInDuration: Double = 0.5,
        fadeOutDuration: Double = 1.0,
        duckingFactor: Float = 0.3
    ) {
        self.requested = requested
        self.mood = mood
        self.style = style
        self.energy = energy
        self.duration = duration
        self.source = source
        self.trackId = trackId
        self.trackTitle = trackTitle
        self.volume = volume
        self.fadeInDuration = fadeInDuration
        self.fadeOutDuration = fadeOutDuration
        self.duckingFactor = duckingFactor
    }
    
    enum CodingKeys: String, CodingKey {
        case requested, mood, style, energy, duration, source, trackId, trackTitle, volume, fadeInDuration, fadeOutDuration, duckingFactor
    }
    
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.requested = (try? container.decodeIfPresent(Bool.self, forKey: .requested)) ?? false
        self.mood = try? container.decodeIfPresent(String.self, forKey: .mood)
        self.style = try? container.decodeIfPresent(String.self, forKey: .style)
        self.energy = try? container.decodeIfPresent(String.self, forKey: .energy)
        
        if let d = try? container.decodeIfPresent(Double.self, forKey: .duration) {
            self.duration = d
        } else if let i = try? container.decodeIfPresent(Int.self, forKey: .duration) {
            self.duration = Double(i)
        } else {
            self.duration = nil
        }
        
        self.source = (try? container.decodeIfPresent(String.self, forKey: .source)) ?? "metalcraft_library"
        self.trackId = try? container.decodeIfPresent(String.self, forKey: .trackId)
        self.trackTitle = try? container.decodeIfPresent(String.self, forKey: .trackTitle)
        
        if let v = try? container.decodeIfPresent(Float.self, forKey: .volume) {
            self.volume = v
        } else if let d = try? container.decodeIfPresent(Double.self, forKey: .volume) {
            self.volume = Float(d)
        } else {
            self.volume = 0.7
        }
        
        self.fadeInDuration = (try? container.decodeIfPresent(Double.self, forKey: .fadeInDuration)) ?? 0.5
        self.fadeOutDuration = (try? container.decodeIfPresent(Double.self, forKey: .fadeOutDuration)) ?? 1.0
        
        if let df = try? container.decodeIfPresent(Float.self, forKey: .duckingFactor) {
            self.duckingFactor = df
        } else if let d = try? container.decodeIfPresent(Double.self, forKey: .duckingFactor) {
            self.duckingFactor = Float(d)
        } else {
            self.duckingFactor = 0.3
        }
    }
    
    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requested, forKey: .requested)
        try container.encodeIfPresent(mood, forKey: .mood)
        try container.encodeIfPresent(style, forKey: .style)
        try container.encodeIfPresent(energy, forKey: .energy)
        try container.encodeIfPresent(duration, forKey: .duration)
        try container.encode(source, forKey: .source)
        try container.encodeIfPresent(trackId, forKey: .trackId)
        try container.encodeIfPresent(trackTitle, forKey: .trackTitle)
        try container.encode(volume, forKey: .volume)
        try container.encode(fadeInDuration, forKey: .fadeInDuration)
        try container.encode(fadeOutDuration, forKey: .fadeOutDuration)
        try container.encode(duckingFactor, forKey: .duckingFactor)
    }
}

// MARK: - EditPlan (Root Contract)

struct EditPlan: Identifiable, Codable, Sendable, Equatable {
    var id: String { planId }
    var schemaVersion: String
    var planId: String
    var createdAt: Date
    var mediaType: MediaType
    var goal: String
    var reasoning: String
    var researchContext: String?
    var adjustments: EditPlanAdjustments
    var operations: [EditPlanOperation]
    var scenes: [EditPlanScene]
    var audioPlan: AudioPlan?
    var targetDuration: Double?
    var aspectRatio: String?
    var output: EditPlanOutput
    
    init(
        schemaVersion: String = "1.0",
        planId: String = UUID().uuidString,
        createdAt: Date = Date(),
        mediaType: MediaType = .image,
        goal: String,
        reasoning: String = "",
        researchContext: String? = nil,
        adjustments: EditPlanAdjustments = .default,
        operations: [EditPlanOperation] = [],
        scenes: [EditPlanScene] = [],
        audioPlan: AudioPlan? = nil,
        targetDuration: Double? = nil,
        aspectRatio: String? = nil,
        output: EditPlanOutput = .default
    ) {
        self.schemaVersion = schemaVersion
        self.planId = planId
        self.createdAt = createdAt
        self.mediaType = mediaType
        self.goal = goal
        self.reasoning = reasoning
        self.researchContext = researchContext
        self.adjustments = adjustments
        self.operations = operations
        self.scenes = scenes
        self.audioPlan = audioPlan
        self.targetDuration = targetDuration
        self.aspectRatio = aspectRatio
        self.output = output
    }
    
    enum CodingKeys: String, CodingKey {
        case schemaVersion, planId, createdAt, mediaType, goal, reasoning, researchContext, adjustments, operations, scenes, audioPlan, targetDuration, aspectRatio, output
        case id, matchedSoundtrack
    }
    
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.schemaVersion = (try? container.decodeIfPresent(String.self, forKey: .schemaVersion)) ?? "1.0"
        self.planId = (try? container.decodeIfPresent(String.self, forKey: .planId)) ?? (try? container.decodeIfPresent(String.self, forKey: .id)) ?? UUID().uuidString
        
        if let d = try? container.decodeIfPresent(Date.self, forKey: .createdAt) {
            self.createdAt = d
        } else if let s = try? container.decodeIfPresent(String.self, forKey: .createdAt) {
            self.createdAt = Self.parseFlexibleDate(s)
        } else {
            self.createdAt = Date()
        }
        
        if let m = try? container.decodeIfPresent(MediaType.self, forKey: .mediaType) {
            self.mediaType = m
        } else if let s = try? container.decodeIfPresent(String.self, forKey: .mediaType) {
            self.mediaType = s.lowercased().contains("video") ? .video : .image
        } else {
            self.mediaType = .video
        }
        
        self.goal = (try? container.decodeIfPresent(String.self, forKey: .goal)) ?? "Creative Media Production"
        self.reasoning = (try? container.decodeIfPresent(String.self, forKey: .reasoning)) ?? ""
        self.researchContext = try? container.decodeIfPresent(String.self, forKey: .researchContext)
        self.adjustments = (try? container.decodeIfPresent(EditPlanAdjustments.self, forKey: .adjustments)) ?? .default
        self.operations = (try? container.decodeIfPresent([EditPlanOperation].self, forKey: .operations)) ?? []
        self.scenes = (try? container.decodeIfPresent([EditPlanScene].self, forKey: .scenes)) ?? []
        self.audioPlan = try? container.decodeIfPresent(AudioPlan.self, forKey: .audioPlan)
        
        if let td = try? container.decodeIfPresent(Double.self, forKey: .targetDuration) {
            self.targetDuration = td
        } else if let ti = try? container.decodeIfPresent(Int.self, forKey: .targetDuration) {
            self.targetDuration = Double(ti)
        } else {
            self.targetDuration = nil
        }
        
        self.aspectRatio = (try? container.decodeIfPresent(String.self, forKey: .aspectRatio)) ?? "9:16"
        self.output = (try? container.decodeIfPresent(EditPlanOutput.self, forKey: .output)) ?? .default
    }
    
    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(schemaVersion, forKey: .schemaVersion)
        try container.encode(planId, forKey: .planId)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(mediaType, forKey: .mediaType)
        try container.encode(goal, forKey: .goal)
        try container.encode(reasoning, forKey: .reasoning)
        try container.encodeIfPresent(researchContext, forKey: .researchContext)
        try container.encode(adjustments, forKey: .adjustments)
        try container.encode(operations, forKey: .operations)
        try container.encode(scenes, forKey: .scenes)
        try container.encodeIfPresent(audioPlan, forKey: .audioPlan)
        try container.encodeIfPresent(targetDuration, forKey: .targetDuration)
        try container.encodeIfPresent(aspectRatio, forKey: .aspectRatio)
        try container.encode(output, forKey: .output)
    }
    
    static func parseFlexibleDate(_ dateStr: String) -> Date {
        let isoFrac = ISO8601DateFormatter()
        isoFrac.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        if let d = isoFrac.date(from: dateStr) { return d }
        
        let iso = ISO8601DateFormatter()
        iso.formatOptions = [.withInternetDateTime]
        if let d = iso.date(from: dateStr) { return d }
        
        let df = DateFormatter()
        df.locale = Locale(identifier: "en_US_POSIX")
        for fmt in [
            "yyyy-MM-dd'T'HH:mm:ss.SSSSSS",
            "yyyy-MM-dd'T'HH:mm:ss.SSS",
            "yyyy-MM-dd'T'HH:mm:ss",
            "yyyy-MM-dd HH:mm:ss",
            "yyyy-MM-dd"
        ] {
            df.dateFormat = fmt
            if let d = df.date(from: dateStr) { return d }
        }
        return Date()
    }
    
    var totalSceneDuration: Double {
        if !scenes.isEmpty {
            return scenes.reduce(0.0) { $0 + $1.duration }
        }
        return targetDuration ?? 0.0
    }
}
