//
//  VideoArtifact.swift
//  MetalCraft
//
//  Represents a persistent, validated video artifact generated by the AI Create engine.
//  Maintains stable local storage references, resolution, duration, file size,
//  and validation status across user navigation, chat sessions, and app restarts.
//

import Foundation

struct VideoArtifact: Identifiable, Codable, Equatable, Sendable {
    let id: UUID
    let generationId: String
    let artifactId: String
    var projectId: UUID?
    var projectName: String?
    var relativePath: String
    var displayName: String
    var duration: Double
    var width: Int
    var height: Int
    var fileSize: Int64
    var formattedFileSize: String
    var createdAt: Date
    var validationStatus: String
    var generationStatus: String
    
    init(
        id: UUID = UUID(),
        generationId: String,
        artifactId: String,
        projectId: UUID? = nil,
        projectName: String? = nil,
        relativePath: String,
        displayName: String,
        duration: Double,
        width: Int = 1080,
        height: Int = 1920,
        fileSize: Int64 = 0,
        formattedFileSize: String = "",
        createdAt: Date = Date(),
        validationStatus: String = "VALIDATED",
        generationStatus: String = "COMPLETED"
    ) {
        self.id = id
        self.generationId = generationId
        self.artifactId = artifactId
        self.projectId = projectId
        self.projectName = projectName
        self.relativePath = relativePath
        self.displayName = displayName
        self.duration = duration
        self.width = width
        self.height = height
        self.fileSize = fileSize
        self.formattedFileSize = formattedFileSize
        self.createdAt = createdAt
        self.validationStatus = validationStatus
        self.generationStatus = generationStatus
    }
    
    /// Resolves the absolute local file URL in the user's Documents directory.
    var fileURL: URL {
        let docs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
        return docs.appendingPathComponent(relativePath)
    }
    
    /// Verifies that the physical file exists and is non-empty on disk.
    var isFileAvailable: Bool {
        let url = fileURL
        guard FileManager.default.fileExists(atPath: url.path) else { return false }
        guard let attrs = try? FileManager.default.attributesOfItem(atPath: url.path),
              let size = attrs[.size] as? Int64, size > 0 else {
            return false
        }
        return true
    }
}
